fm_elfinder:
    instances:
        default:
            locale: fr # Langue
            editor: ckeditor # Editeur utilisé
            fullscreen: true # Taille d'affichage
            theme: smoothness # Thème à utiliser
            connector:
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path:  '%env(APP_PATH_CONTENT_IMAGES_POSTS)%'  # Chemin d'upload
                        upload_allow: ['image/jpeg','image/jpg', 'image/gif', 'image/png',  'image/svg' , 'image/svg+xml',"image/pdf" , 'image/webp', 'application/pdf'] # Fichiers autorisés
                        upload_deny: ['all'] # Fichiers interdits
                        upload_max_size: 2M # Taille maximum
