# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html
fos_ck_editor:
    configs:
        my_config:
            jquery: true
            toolbar: full
            height: '50%'
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters: []
            basicEntities: false;
            entities: false;
            uiColor: "#2E8B57"
            allowedContent: true
    base_path: "bundles/fosckeditor"
    js_path:   "bundles/fosckeditor/ckeditor.js"
twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
