# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

fos_ck_editor:
  base_path: "build/ckeditor"
  js_path:   "build/ckeditor/ckeditor.js"
  configs:
    my_config:
      jquery: true
      toolbar: full
      height: '50%'
      filebrowserBrowseRoute: elfinder
      filebrowserBrowseRouteParameters: []
      basicEntities: false;
      entities: false;
      uiColor: "#2E8B57"
      allowedContent: true
#      extraPlugins: "GoogleWebFonts" ## "ckeditor-gwf-plugin" ##"GoogleWebFonts"
