vich_uploader:
    db_driver: orm
    metadata:
        type: attribute    # or annotation
#    mappings:
#        products:
#            uri_prefix: /images/products
#            upload_destination: '%kernel.project_dir%/public/images/products'
    mappings:
        content_images:
            directory_namer: App\Upload\Namer\ConventionedDirectoryNamer
            uri_prefix:         '%env(APP_PATH_CONTENT_IMAGES)%'
            upload_destination: '%kernel.project_dir%/public/%env(APP_PATH_CONTENT_IMAGES)%'
            inject_on_load:     true # injecte l'image au chargement du formulaire
            delete_on_update:   true
            delete_on_remove:   true
