#index:
#    path: /
#    controller: App\Controller\Front\FrontController::index
login:
  path: /login
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
  defaults:
    route: app_login
    permanent: true

admin:
  path: /admin
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
  defaults:
    route: admin_index
    permanent: true

hermes_admin:
  # loads routes from the PHP annotations of the controllers found in that directory
  resource: '../src/Controller/Admin/AdminController.php'
  type:     annotation

hermes_stripe:
  # loads routes from the PHP annotations of the controllers found in that directory
  resource: '../src/Controller/Stripe'
  type:     annotation

hermes_front:
  # loads routes from the PHP annotations of the controllers found in that directory
  resource: '../src/Controller/Front'
  type:     annotation
