#index:
#    path: /
#    controller: App\Controller\Front\FrontController::homepage

sitemap_redirect:
  path: /sitemap.xml
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
  defaults:
    route: sitemap
#    path: /{_locale}/sitemap.xml
    permanent: true

login:
  path: /login
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
  defaults:
    route: app_login
    permanent: true

admin:
  path: /admin
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
  defaults:
    route: admin_index
    permanent: true

daddl3_symfonyckeditor5webpackvite_imageupload_upload:
    path: /ckeditor/upload
    controller: daddl3\SymfonyCKEditor5WebpackViteBundle\Controller\ImageUploadController::upload
    methods: [POST]

daddl3_symfonyckeditor5webpackvite_imageupload_browse:
    path: /ckeditor/browse
    controller: daddl3\SymfonyCKEditor5WebpackViteBundle\Controller\ImageUploadController::browse
    methods: [GET]

hermes_admin:
  # loads routes from the PHP annotations of the controllers found in that directory
  resource: '../src/Controller/Admin/AdminController.php'
  type:     annotation

hermes_front:
  # loads routes from the PHP annotations of the controllers found in that directory
  resource: '../src/Controller/Front'
  type:     annotation


# homepage:
#   path: /
#   controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
#   defaults:
#     path: /%APP_DEFAULT_LOCALE%/
#     permanent: false

# homepage:
#   path: /{text}
#   controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
#   defaults:
#     path: /fr/home
#     permanent: true
