services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tests\Behat\:
        resource: '../tests/Behat/*'

    Tests\DataFixtures\:
        resource: '../tests/DataFixtures/*'